services:

    #
    # Form Types
    #
    store.geo.form_type.address:
        class: %store.geo.form_type.address.class%
        arguments:
            - @elcodi.factory.address
            - %elcodi.core.geo.entity.country.class%
        tags:
            - { name: form.type, alias: store_geo_form_type_address }
