services:

    #
    # Form Types
    #
    admin.geo.form_type.address:
        class: %admin.geo.form_type.address.class%
        calls:
            - [setFactory, [@elcodi.factory.address]]
        tags:
            - { name: form.type, alias: admin_geo_form_type_address }
