services:

    #
    # Services
    #
    elcodi.service.store_address_manager:
        class: Elcodi\Admin\GeoBundle\Services\StoreAddressManager
        arguments:
            configuration_manager: @elcodi.manager.configuration
            address_repository: @elcodi.repository.address

    elcodi.admin.geo.form.location_selector_builder:
        class: Elcodi\Admin\GeoBundle\Form\LocationSelectorBuilder
        arguments:
            location_provider: @elcodi.location_provider
