services:

    #
    # Event Listeners
    #
    admin.user.event_listener.remember_password:
        class: %admin.user.event_listener.remember_password.class%
        arguments:
            - @mailer
            - @templating
            - @security.token_storage
            - %bamboo_store_firewall%
        tags:
            - { name: kernel.event_listener, event: password.remember, method: onPasswordRemember }
            - { name: kernel.event_listener, event: password.recover, method: onPasswordRecover }
