services:

    #
    # Authenticator
    #
    admin.user.security.one_time_login_authenticator:
        class: Elcodi\Admin\UserBundle\Security\OneTimeLoginAuthenticator
        arguments:
            - @elcodi.object_manager.admin_user
            - @elcodi.repository.admin_user
