services:

    store.product.service.product_collection_provider:
        class: Elcodi\Store\ProductBundle\Services\ProductCollectionProvider
        parent: elcodi.provider.product_collection

    store.product.service.store_category_tree:
        class: Elcodi\Store\ProductBundle\Services\StoreCategoryTree
        arguments:
            category_tree_service: @elcodi.provider.category_tree
            load_only_categories_with_products: %elcodi.core.product.load_only_categories_with_products%
            key: %elcodi.core.product.cache_key%
        calls:
            - [setCache, [@doctrine_cache.providers.elcodi_categories]]
            - [setEncoder, [@elcodi.json_encoder]]
