services:

    #
    # Form Types
    #
    elcodi.admin.rule.form_type.rule:
        class: %elcodi.admin.rule.form_type.rule.class%
        arguments:
            entity: %elcodi.core.rule.entity.rule.class%
        tags:
            - { name: form.type, alias: elcodi_admin_rule_form_type_rule }
