build: false
platform: x86
clone_folder: c:\projects\elcodi

environment:
  composer_oauth_token:
    secure: dt/I7q2VlRVoaVYSvTSGjLP6whbow65qLUbZZXhy01ptcsoLtPFdpJysswEIghoP

matrix:
  fast_finish: true

cache:
  - '%LOCALAPPDATA%\Composer\files'

init:
  - SET PATH=C:\Program Files\OpenSSL;c:\tools\php;C:\tools\SQLite\;%PATH%

install:
  - cinst -y OpenSSL.Light
  - cinst -y php
  - cinst -y sqlite
  - cd c:\tools\php
  - copy php.ini-production php.ini /Y
  - echo extension_dir=ext >> php.ini
  - echo memory_limit=1G >> php.ini
  - echo date.timezone="UTC" >> php.ini
  - echo extension=php_curl.dll >> php.ini
  - echo extension=php_fileinfo.dll >> php.ini
  - echo extension=php_gd2.dll >> php.ini
  - echo extension=php_intl.dll >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_pdo_sqlite.dll >> php.ini
  - cd %APPVEYOR_BUILD_FOLDER%
  - php -r "readfile('http://getcomposer.org/installer');" | php
  - php composer.phar config -g github-oauth.github.com %composer_oauth_token%
  - php composer.phar install --prefer-dist --no-interaction --no-progress

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - bin\behat.bat -fprogress --tags="~javascript"
  - bin\phpunit.bat --verbose
