services:

    #
    # Event listeners
    #
    store.abstract_email_sender_event_listener:
        class: %store.abstract_email_sender_event_listener.class%
        abstract: true
        arguments:
            - @mailer
            - @twig
            - @elcodi.repository.page
            - @=elcodi_config("store.email")
