services:

    #
    # Twig Extension loader
    #
    twig.stringloader:
        class: Twig_Extension_StringLoader
        tags:
            - { name: twig.extension }

    #
    # Twig Extensions
    #
    store.twig_extension.store_page:
        class: Elcodi\Store\PageBundle\Twig\PageExtension
        arguments:
            - @elcodi.repository.page
        tags:
            - { name: twig.extension }
