services:

    #
    # Form Types
    #
    elcodi.admin.attribute.form_type.attribute:
        class: %elcodi.admin.attribute.form_type.attribute.class%
        calls:
            - [setFactory, [@elcodi.factory.attribute]]
        tags:
            - { name: form.type, alias: elcodi_admin_attribute_form_type_attribute }
