services:

    #
    # Menu builders
    #
    elcodi_admin.menu_builder.cart:
        class: Elcodi\Admin\CartBundle\Builder\MenuBuilder
        arguments:
            - @elcodi.factory.menu_node
        tags:
            - { name: menu.builder }
