parameters:

    #
    # Entity classes
    #
    elcodi.admin.cartcoupon.form_type.order_coupon.class: Admin\AdminCartCouponBundle\Form\Type\OrderCouponType
    elcodi.admin.cartcoupon.form_type.cart_coupon.class: Admin\AdminCartCouponBundle\Form\Type\CartCouponType
