services:

    #
    # Event Listeners
    #
    store.payment.event_listener.payment:
        class: %store.payment.event_listener.payment.class%
        arguments:
            cart_wrapper: @elcodi.cart_wrapper
            cart_order_transformer: @elcodi.cart_order_transformer
            order_manager: @elcodi.order_manager
            order_repository: @elcodi.repository.order
        tags:
            - { name: kernel.event_listener, event: payment.order.load, method: onPaymentOrderLoad }
            - { name: kernel.event_listener, event: payment.order.success, method: onPaymentOrderSuccess }
            - { name: kernel.event_listener, event: payment.order.done, method: onPaymentOrderDone }
