services:

    #
    # Form Types
    #
    elcodi.admin.store.form_type.store_settings:
        class: Elcodi\Admin\StoreBundle\Form\Type\StoreSettingsType
        arguments:
            - %elcodi.entity.currency.class%
            - %elcodi.entity.language.class%
        calls:
            - [setFactory, [@elcodi.factory.store]]
        tags:
            - { name: form.type, alias: elcodi_admin_store_form_type_store_settings }

    elcodi.admin.store.form_type.store_address:
        class: Elcodi\Admin\StoreBundle\Form\Type\StoreAddressType
        calls:
            - [setFactory, [@elcodi.factory.store]]
        tags:
            - { name: form.type, alias: elcodi_admin_store_form_type_store_address }

    elcodi.admin.store.form_type.store_corporate:
        class: Elcodi\Admin\StoreBundle\Form\Type\StoreCorporateType
        arguments:
            - %elcodi.entity.image.class%
        calls:
            - [setFactory, [@elcodi.factory.store]]
        tags:
            - { name: form.type, alias: elcodi_admin_store_form_type_store_corporate }
