security:
    access_control:

        # admin
        login_area:
            path: ^/%bamboo_admin_prefix%/login
            roles: IS_AUTHENTICATED_ANONYMOUSLY

        password_area:
            path: ^/%bamboo_admin_prefix%/password
            roles: IS_AUTHENTICATED_ANONYMOUSLY

        admin_area:
            path: ^/%bamboo_admin_prefix%/
            roles: ROLE_ADMIN

        # store
        customer_area:
            path: ^/user(/|$)
            roles: ROLE_CUSTOMER

        checkout_area:
            path: ^/checkout/
            roles: ROLE_CUSTOMER

        public_area:
            path: ^/
            roles: IS_AUTHENTICATED_ANONYMOUSLY
