imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

monolog:
    handlers:
        main:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: error
        firephp:
            type:  firephp
            level: critical

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

#bc_bootstrap:
    #less_filter: lessphp
    #assets_dir: %kernel.root_dir%/../vendor/twbs/bootstrap
    #jquery_path: %kernel.root_dir%/../vendor/jquery/jquery/jquery-1.9.1.js

# Assetic Configuration
assetic:
    bundles: ['StoreCoreBundle']
    debug:          "%kernel.debug%"
    use_controller: false

    #java: /usr/bin/java
    filters:
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

doctrine_cache:
    providers:
        elcodi:
            type: array

elcodi_media:
    images:
        filesystem: gaufrette.local_filesystem

knp_gaufrette:
    adapters:
        local:
            local:
                directory: %kernel.cache_dir%/tmp/gaufrette
                create: true
    filesystems:
        local:
            adapter:    local

free_payment:
    payment_success:
        route: store_order_thanks
        order_append: true
        order_append_field: orderId
