admin_core:
    resource: "@AdminCoreBundle/Resources/config/routing.yml"

admin_user:
    resource: "@AdminUserBundle/Resources/config/routing.yml"

admin_cart:
    resource: "@AdminCartBundle/Resources/config/routing.yml"

admin_banner:
    resource: "@AdminBannerBundle/Resources/config/routing.yml"

admin_coupon:
    resource: "@AdminCouponBundle/Resources/config/routing.yml"

admin_currency:
    resource: "@AdminCurrencyBundle/Resources/config/routing.yml"

admin_product:
    resource: "@AdminProductBundle/Resources/config/routing.yml"

admin_rule:
    resource: "@AdminRuleBundle/Resources/config/routing.yml"

admin_media:
    resource: "@AdminMediaBundle/Resources/config/routing.yml"

admin_newsletter:
    resource: "@AdminNewsletterBundle/Resources/config/routing.yml"

admin_login_check:
    path:  /login_check

admin_logout:
    path: /logout

core_media_bundle:
    resource: "@ElcodiMediaBundle/Resources/config/routing.yml"