store_core:
    resource: "@StoreCoreBundle/Resources/config/routing.yml"

store_product:
    resource: "@StoreProductBundle/Resources/config/routing.yml"

store_user:
    resource: "@StoreUserBundle/Resources/config/routing.yml"

store_cart:
    resource: "@StoreCartBundle/Resources/config/routing.yml"

store_cart_coupon:
    resource: "@StoreCartCouponBundle/Resources/config/routing.yml"

store_currency:
    resource: "@StoreCurrencyBundle/Resources/config/routing.yml"

payment:
    resource: "@PaymentBridgeBundle/Resources/config/routing.yml"

store_login_check:
    path:  /login_check

store_logout:
    path: /logout

core_media_bundle:
    resource: "@ElcodiMediaBundle/Resources/config/routing.yml"
