jms_security_extra:
    secure_all_services: false
    expressions: true

imports:
    - { resource: @ElcodiUserBundle/Resources/security/encoders.yml }
    - { resource: @ElcodiUserBundle/Resources/security/providers.yml }
    - { resource: @StoreCoreBundle/Resources/config/firewalls.yml }
    - { resource: @StoreCoreBundle/Resources/config/accessControl.yml }
    - { resource: @StoreCoreBundle/Resources/config/roles.yml }