services:

    #
    # Form Types
    #
    elcodi.admin.currency.form_type.currency:
        class: %elcodi.admin.currency.form_type.currency.class%
        calls:
            - [setFactory, [@elcodi.factory.currency]]
        tags:
            - { name: form.type, alias: elcodi_admin_currency_form_type_currency }

    elcodi.admin.currency.form_type.money:
        class: %elcodi.admin.currency.form_type.money.class%
        arguments:
            currency_wrapper: @elcodi.wrapper.currency
            default_currency: %elcodi.core.currency.default_currency%
        tags:
            - { name: form.type, alias: money_object }
