services:

    #
    # Services
    #
    elcodi.admin.product.services.category_sorter:
        class: %elcodi.admin.product.services.category_sorter.class%
        arguments:
            category_repository: @elcodi.repository.category
            category_object_manager: @elcodi.object_manager.category
