services:

    #
    # Form Types
    #
    store.form_type.login:
        class: %store.form_type.login.class%
        arguments:
            router: @router
        tags:
            - { name: form.type, alias: store_user_form_type_login }

    store.form_type.register:
        class: %store.form_type.register.class%
        arguments:
            customer_namespace: %elcodi.core.user.entity.customer.class%
        tags:
            - { name: form.type, alias: store_user_form_type_register }

    store.form_type.profile:
        class: %store.form_type.profile.class%
        arguments:
            customer_namespace: %elcodi.core.user.entity.customer.class%
        tags:
            - { name: form.type, alias: store_user_form_type_profile }

    store.form_type.password_remember:
        class: %store.form_type.password_remember.class%
        tags:
            - { name: form.type, alias: store_user_form_type_password_remember }

    store.form_type.password_recover:
        class: %store.form_type.password_recover.class%
        tags:
            - { name: form.type, alias: store_user_form_type_password_recover }
