parameters:

    #
    # Entity classes
    #
    elcodi.admin.page.form_type.page.class: Elcodi\Admin\PageBundle\Form\Type\PageType
    elcodi.admin.page.form_type.blog_post.class: Elcodi\Admin\PageBundle\Form\Type\BlogPostType
    elcodi.admin.page.form_type.email.class: Elcodi\Admin\PageBundle\Form\Type\EmailType

    #
    # Event Listeners
    #
    elcodi.admin.page.form_event_listener.permanent_page.class: Elcodi\Admin\PageBundle\Form\EventListener\PermanentPageSubscriber
