parameters:

    #
    # Pagination fields
    #
    elcodi.admin.currency.pagination.currency.fields:
        - id
        - iso
        - symbol
        - createdAt
        - updatedAt
        - enabled
    elcodi.admin.currency.pagination.currency_exchange_rate.fields:
        - id
        - exchangeRate
