services:

    jms_i18n_routing.locale_choosing_listener:
        class: %jms_i18n_routing.locale_choosing_listener.class%
        public: false
        arguments:
            - %jms_i18n_routing.default_locale%
            - @elcodi.languages_iso_array
            - @jms_i18n_routing.locale_resolver

    jms_i18n_routing.pattern_generation_strategy.default:
        class: %jms_i18n_routing.pattern_generation_strategy.class%
        arguments:
            - %jms_i18n_routing.strategy%
            - @translator
            - @elcodi.languages_iso_array
            - %kernel.cache_dir%
            - %jms_i18n_routing.catalogue%
            - %jms_i18n_routing.default_locale%

    #
    # Page renderer
    #
    bamboo.page.renderer.template_renderer:
        class: Elcodi\Component\Page\Renderer\TemplatedPageRenderer
        arguments:
            - @templating.engine.twig
            - "Layout:_static.html.twig"
            - [@=elcodi_config("store.template")]

    #
    # Store tracker
    #
    elcodi.store_tracker:
        class: stdClass
        factory_service: elcodi.manager.configuration
        factory_method: get
        arguments: ['store.tracker']

    #
    # Store address
    #
    elcodi.store_address:
        class: %elcodi.entity.address.class%
        factory_service: elcodi.service.store_address_manager
        factory_method: getStoreAddress
