parameters:

    #
    # Entity classes
    #
    elcodi.admin.currency.form_type.currency.class: Admin\AdminCurrencyBundle\Form\Type\CurrencyType
    elcodi.admin.currency.form_type.currency_exchange_rate.class: Admin\AdminCurrencyBundle\Form\Type\CurrencyExchangeRateType
    elcodi.admin.currency.form_type.money.class: Admin\AdminCurrencyBundle\Form\Type\MoneyType
