parameters:

    #
    # Services
    #
    elcodi.metric_intervals_resolver.class: Elcodi\Admin\MetricBundle\Services\MetricIntervalsResolver

    #
    # Twig Extensions
    #
    elcodi.twig_extension.metric_intervals.class: Elcodi\Admin\MetricBundle\Twig\MetricIntervalsExtension
