services:

    #
    # Twig Extensions
    #
    elcodi.twig_extension.metric_intervals:
        class: Elcodi\Admin\MetricBundle\Twig\MetricIntervalsExtension
        arguments:
            - @elcodi.metric_intervals_resolver
        tags:
            - { name: twig.extension }
