services:

    #
    # Twig Extensions
    #
    elcodi.twig_extension.metric_intervals:
        class: %elcodi.twig_extension.metric_intervals.class%
        arguments:
            - @elcodi.metric_intervals_resolver
        tags:
            - { name: twig.extension }
