services:

    store.product.services.product_collection_provider:
        class: %store.product.services.product_collection_provider.class%
        arguments:
            product_repository: @=service("doctrine.orm.entity_manager").getRepository("ElcodiProductBundle:Product")
            locale: %locale%
