services:

    #
    # Event Listeners
    #
    store.user.event_listener.password:
        class: %store.user.event_listener.password.class%
        arguments:
            mailer: @mailer
            templating: @templating
            security_context: @security.context
        tags:
            - { name: kernel.event_listener, event: password.remember, method: onPasswordRemember }
            - { name: kernel.event_listener, event: password.recover, method: onPasswordRecover }