parameters:

    #
    # Services
    #
    elcodi_plugin.product_csv.exporter.class: Elcodi\Plugin\ProductCsv\Services\ProductExporter

    #
    # Renderers
    #
    elcodi_plugin.product_csv.renderer.class: Elcodi\Plugin\ProductCsv\Templating\TwigRenderer
