services:

    #
    # Form Types
    #
    elcodi.admin.product.form_type.coupon:
        class: %elcodi.admin.coupon.form_type.coupon.class%
        arguments:
            - %elcodi.entity.rule.class%
        calls:
            - [setFactory, [@elcodi.factory.coupon]]
        tags:
            - { name: form.type, alias: elcodi_admin_coupon_form_type_coupon }
