parameters:

    #
    # Form Types
    #
    store.geo.form_type.address.class: Elcodi\Store\GeoBundle\Form\Type\AddressType

    #
    # Services
    #
    elcodi.store.geo.form.location_selector_builder.class: Elcodi\Store\GeoBundle\Form\LocationSelectorBuilder
