services:

    #
    # Form Types
    #
    store.geo.form_type.address:
        class: %store.geo.form_type.address.class%
        calls:
            - [setFactory, [@elcodi.factory.address]]
        tags:
            - { name: form.type, alias: store_geo_form_type_address }
