parameters:

    #
    # Pagination fields
    #
    elcodi.admin.attribute.pagination.attribute.fields:
        - id
        - name
        - displayName
        - enabled
    elcodi.admin.attribute.pagination.value.fields:
            - id
            - name
            - displayName
            - enabled

