parameters:

    #
    # Factories
    #
    store.connect.factory.authorization.class: Elcodi\Store\ConnectBundle\Factory\AuthorizationFactory

    #
    # Services
    #
    store.connect.service.oauth_provider.class: Elcodi\Store\ConnectBundle\Services\OAuthUserProvider
