services:

    #
    # Factories
    #

    #
    # Factory for Authorization entities
    #
    store.connect.factory.authorization:
        class: %store.connect.factory.authorization.class%
        calls:
            - [setEntityNamespace, ["%store.connect.entity.authorization.class%"]]
