services:

    #
    # Factories
    #

    #
    # Factory for Authorization entities
    #
    store.connect.factory.authorization:
        class: Elcodi\Store\ConnectBundle\Factory\AuthorizationFactory
        calls:
            - [setEntityNamespace, ["%store.connect.entity.authorization.class%"]]
