services:

    #
    # Services
    #
    store.connect.service.oauth_provider:
        class: Elcodi\Store\ConnectBundle\Services\OAuthUserProvider
        arguments:
            - @security.user.provider.concrete.customer
            - @store.connect.director.authorization
            - @elcodi.director.customer
            - @elcodi.object_manager.customer
            - @elcodi.event_dispatcher.user
