parameters:

    #
    # Event Listeners
    #
    store.core.event_listener.store_disabled.class: Elcodi\Store\CoreBundle\EventListener\StoreUnavailableEventListener
    store.core.event_listener.store_under_construction.class: Elcodi\Store\CoreBundle\EventListener\StoreUnavailableEventListener

    #
    # Twig extensions
    #
    elcodi.twig_extension.encrypt.class: Elcodi\Store\CoreBundle\Twig\EncryptExtension
    elcodi.twig_extension.referrer.class: Elcodi\Store\CoreBundle\Twig\ReferrerExtension

    #
    # Services
    #
    store.core.services.template_locator.class: Elcodi\Store\CoreBundle\Services\TemplateLocator
