services:

    #
    # Event Listeners
    #
    store.core.event_listener.store_disabled:
        class: %store.core.event_listener.store_disabled.class%
        arguments:
            twig: @templating
            template_bundle: @=elcodi_config("store.template")
            store_enabled: @=elcodi_config("store.enabled")
            bamboo_admin_prefix: %bamboo_admin_prefix%
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: checkIfStoreIsDisabled, priority: 41 }

    store.core.event_listener.store_under_construction:
        class: %store.core.event_listener.store_under_construction.class%
        arguments:
            twig: @templating
            template_bundle: @=elcodi_config("store.template")
            store_enabled: @=elcodi_config("store.under_construction")
            bamboo_admin_prefix: %bamboo_admin_prefix%
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: checkIfStoreIsUnderConstruction, priority: 40 }
