services:

    #
    # Event Listeners
    #
    store.cart.event_listener.cart_customer:
        class: %store.cart.event_listener.cart_customer.class%
        arguments:
            security_context: @security.context
            cart_wrapper: @elcodi.cart_wrapper
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
