services:

    #
    # Menu builders
    #
    elcodi_admin.menu_builder.plugin_list:
        class: Elcodi\Admin\PluginBundle\Builder\MenuBuilder
        arguments:
            - @elcodi.factory.menu_node
        tags:
            - { name: menu.builder }

    elcodi_admin.menu_builder.plugins:
        class: Elcodi\Admin\PluginBundle\Builder\PluginMenuBuilder
        arguments:
            - @elcodi.factory.menu_node
            - @router
            - @elcodi.enabled_plugins
        tags:
            - { name: menu.builder }
