parameters:

    #
    # Services
    #
    store.payment.service.payment_bridge.class: Elcodi\Store\PaymentBridgeBundle\Services\PaymentBridge

    #
    # Event Listeners
    #
    store.payment.event_listener.cart_paid.class: Elcodi\Store\PaymentBridgeBundle\EventListener\CartPaidEventListener
    store.payment.event_listener.order_to_paid.class: Elcodi\Store\PaymentBridgeBundle\EventListener\OrderToPaidEventListener
