#
# Payment bundles specific configuration
#

free_payment:
    payment_success:
        route: store_order_thanks
        order_append: true
        order_append_field: id

paypal_web_checkout:
    business: %paypal_web_checkout_recipient%
    payment_process:
        route: store_payment_process
    payment_success:
        route: store_order_thanks
        order_append: true
        order_append_field: id
    payment_cancel:
        route: store_homepage
        order_append: false
    payment_fail:
        route: store_checkout_payment_fail
        order_append: true
        order_append_field: id

paymill:
    public_key: %paymill_public_key%
    private_key: %paymill_private_key%
    payment_success:
        route: store_order_thanks
        order_append: true
        order_append_field: id
    payment_fail:
        route: store_checkout_payment_fail
        order_append: true
    form:
        submit_label: Continue
        submit_css_class: "btn btn-primary"
