parameters:

    #
    # Form Types
    #
    store.cart.form_type.cart.class: Elcodi\Store\CartBundle\Form\Type\CartType
    store.cart.form_type.cart_line.class: Elcodi\Store\CartBundle\Form\Type\CartLineType

    #
    # Event listeners
    #
    store.cart.event_listener.shipping_appliance.class: Elcodi\Store\CartBundle\EventListener\ShippingApplianceEventListener
