services:

    #
    # Event listeners
    #
    store.cart.event_listener.shipping_appliance:
        class: %store.cart.event_listener.shipping_appliance.class%
        arguments:
            - @elcodi.event_dispatcher.cart
            - @elcodi.provider.shipping_range
            - @elcodi.resolver.shipping_range
        tags:
            - { name: kernel.event_listener, event: cart.onload, method: removeInvalidShippingRange, priority: 8 }
            - { name: kernel.event_listener, event: cart.onload, method: loadCheapestShippingRange, priority: 9 }
