services:

    #
    # Form Types
    #
    store.cart.form_type.cart:
        class: %store.cart.form_type.cart.class%
        arguments:
            - @router
        calls:
            - [setFactory, [@elcodi.factory.cart]]
        tags:
            - { name: form.type, alias: store_cart_form_type_cart }

    store.cart.form_type.cart_line:
        class: %store.cart.form_type.cart_line.class%
        calls:
            - [setFactory, [@elcodi.factory.cart_line]]
        tags:
            - { name: form.type, alias: store_cart_form_type_cart_line }
