#
# API routes
#
elcodi_metric:
    resource: "@ElcodiMetricBundle/Resources/config/routing.yml"

elcodi_comment:
    resource: "@ElcodiCommentBundle/Resources/config/routing.yml"
    prefix: /%bamboo_api_prefix%

elcodi_location:
    resource: "@ElcodiGeoBundle/Resources/config/routing.yml"
    prefix: /%bamboo_api_prefix%
