#
# Plugins routes
#
elcodi_plugin_product_csv:
    resource: "@ElcodiProductCsvBundle/Resources/config/routing.yml"
    prefix: /plugin/product-csv

elcodi_store_setup_wizard:
    resource: "@ElcodiStoreSetupWizardBundle/Resources/config/routing.yml"
    prefix: /plugin/setup-wizard
