imports:
    - { resource: config_dev.yml }
    - { resource: parameters_test.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        connections:
            default:
                dbname:   "%database_name%_test"
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        metadata_cache_driver: array
        auto_mapping: true
        query_cache_driver:
            type: array
        result_cache_driver:
            type: array